DROP TABLE sprzedaze CASCADE;
DROP TABLE samochody CASCADE;
DROP TABLE modele CASCADE;
DROP TABLE marki CASCADE;
DROP TABLE paliwo CASCADE;
DROP TABLE klienci CASCADE;
DROP TABLE pracownicy CASCADE;
DROP TABLE salony CASCADE;