DROP FUNCTION nowePaliwo(VARCHAR);

DROP FUNCTION nowaMarka(VARCHAR);

DROP FUNCTION nowySalon (VARCHAR, VARCHAR);

DROP FUNCTION nowyModel(INTEGER, VARCHAR, INTEGER, NUMERIC(4,2), INTEGER, VARCHAR, INTEGER, INTEGER);

DROP FUNCTION nowySamochod(INTEGER, INTEGER, VARCHAR);

DROP FUNCTION nowyPracownik (VARCHAR, VARCHAR, VARCHAR, NUMERIC(7, 2), INTEGER);

DROP FUNCTION nowyKlient (VARCHAR, VARCHAR, VARCHAR, VARCHAR);

DROP FUNCTION nowaSprzedaz (INTEGER, INTEGER, INTEGER, INTEGER, DATE);

DROP FUNCTION czytajPaliwo();

DROP FUNCTION czytajModele();

DROP FUNCTION czytajSamochody();

DROP FUNCTION czytajPracownicy();

DROP FUNCTION czytajKlienci();

DROP FUNCTION czytajSalony();

DROP FUNCTION czytajSprzedaze();